// src/components/worksheets/IRMAAWorksheet.tsx
"use client";
import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { formatCurrency } from "../../utils";
import { Card } from "../catalyst/card/Card";
import IRMAAAutoInsights from "../insights/IRMAAAutoInsights";
import IRMAAThresholdBar from "../../charts/IRMAAThresholdBar";
export default function IRMAAWorksheet({ chart, insights }) {
    const { userMAGI, thresholds, surcharges, currentTierIndex } = chart;
    const hasData = userMAGI > 0;
    const currentTier = currentTierIndex <= 0 ? 0 : Math.min(currentTierIndex, thresholds.length - 1);
    const nextThreshold = thresholds[currentTier + 1];
    const roomBeforeNext = nextThreshold !== undefined ? Math.max(0, nextThreshold - userMAGI) : 0;
    const monthlySurcharge = surcharges[currentTier] ?? 0;
    const annualSurcharge = monthlySurcharge * 12;
    const tierLabel = currentTier === 0 ? "Baseline (Tier 0)" : `Tier ${currentTier}`;
    return (_jsxs(Card, { children: [_jsx("h3", { className: "text-xl font-semibold mb-3", children: "Medicare IRMAA Worksheet" }), _jsx("p", { className: "text-sm text-gray-500 mb-6", children: "Medicare premiums can increase when your Modified Adjusted Gross Income (MAGI) crosses certain thresholds. This worksheet shows where your income falls in the IRMAA tiers and how this may affect your Medicare premiums." }), !hasData ? (_jsx("div", { className: "text-gray-500 text-sm", children: "Enter income details to see how IRMAA tiers may affect your Medicare premiums. This is an educational simulation only." })) : (_jsxs(_Fragment, { children: [_jsxs("div", { className: "mb-6", children: [_jsx("h4", { className: "text-base font-semibold mb-2", children: "Medicare IRMAA Insights" }), _jsx(IRMAAAutoInsights, { insights: insights })] }), _jsxs("div", { className: "mb-8", children: [_jsx("h4", { className: "text-sm font-semibold mb-2", children: "Where Your Income Falls in the IRMAA Tiers" }), _jsx(IRMAAThresholdBar, { chart: chart })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4 mb-6", children: [_jsxs("div", { className: "rounded-lg border border-gray-100 bg-gray-50 p-3", children: [_jsx("p", { className: "text-xs font-medium text-gray-500 mb-1", children: "Your MAGI (Approx.)" }), _jsx("p", { className: "text-2xl font-bold text-gray-900", children: formatCurrency(userMAGI) }), _jsx("p", { className: "mt-1 text-xs text-gray-500", children: "This is your Modified Adjusted Gross Income, the number Medicare uses to place you in an IRMAA tier." })] }), _jsxs("div", { className: "rounded-lg border border-gray-100 bg-gray-50 p-3", children: [_jsx("p", { className: "text-xs font-medium text-gray-500 mb-1", children: "Current IRMAA Tier" }), _jsx("p", { className: "text-2xl font-bold text-gray-900", children: tierLabel }), _jsx("p", { className: "mt-1 text-xs text-gray-500", children: "This tier determines whether your Medicare premiums include an extra IRMAA surcharge." })] }), _jsxs("div", { className: "rounded-lg border border-gray-100 bg-gray-50 p-3", children: [_jsx("p", { className: "text-xs font-medium text-gray-500 mb-1", children: "Room Before Next Tier" }), _jsx("p", { className: "text-2xl font-bold text-gray-900", children: nextThreshold !== undefined
                                            ? formatCurrency(roomBeforeNext)
                                            : "—" }), _jsx("p", { className: "mt-1 text-xs text-gray-500", children: nextThreshold !== undefined ? (_jsxs(_Fragment, { children: ["You can increase your MAGI by approximately", " ", formatCurrency(roomBeforeNext), " before reaching the next Medicare surcharge tier."] })) : ("You are in the highest IRMAA tier under current rules; additional income will not increase IRMAA surcharges further.") })] }), _jsxs("div", { className: "rounded-lg border border-gray-100 bg-gray-50 p-3", children: [_jsx("p", { className: "text-xs font-medium text-gray-500 mb-1", children: "Estimated Annual IRMAA Surcharge" }), _jsx("p", { className: "text-2xl font-bold text-gray-900", children: annualSurcharge > 0 ? formatCurrency(annualSurcharge) : "$0" }), _jsx("p", { className: "mt-1 text-xs text-gray-500", children: "This is an approximate annual amount, based on the monthly IRMAA surcharge for your current tier." })] })] }), _jsxs("div", { className: "mb-4 rounded-lg border border-blue-100 bg-blue-50 p-4", children: [_jsx("h4", { className: "text-sm font-semibold mb-2", children: "What This Means For You" }), _jsxs("ul", { className: "list-disc pl-4 text-xs text-gray-700 space-y-1", children: [_jsxs("li", { children: ["At your current income level,", " ", annualSurcharge > 0
                                                ? "your Medicare premiums include an additional IRMAA surcharge."
                                                : "your Medicare premiums are not affected by IRMAA."] }), _jsx("li", { children: "IRMAA uses income from two years ago, so changes you make today may affect future Medicare premiums, not just this year." }), _jsx("li", { children: "Roth conversions, large capital gains, or unusually high income in a single year can push you into a higher IRMAA tier." }), nextThreshold !== undefined && roomBeforeNext > 0 && (_jsxs("li", { children: ["You have about ", formatCurrency(roomBeforeNext), " of room before reaching the next IRMAA tier under current rules."] })), _jsx("li", { children: "Consider how one-time income events fit into your broader retirement plan and Medicare costs over time." })] })] }), _jsxs("div", { className: "mb-4 rounded-lg border border-gray-100 bg-white p-4", children: [_jsx("h4", { className: "text-sm font-semibold mb-2", children: "Why IRMAA Happens" }), _jsx("p", { className: "text-xs text-gray-600 mb-2", children: "Medicare charges an Income-Related Monthly Adjustment Amount (IRMAA) when your MAGI crosses certain IRS-defined thresholds. These thresholds define several tiers, each with its own monthly surcharge added to your Medicare premiums." }), _jsxs("ul", { className: "list-disc pl-4 text-xs text-gray-600 space-y-1", children: [_jsx("li", { children: "Tier 0 \u2013 no IRMAA surcharge (baseline premium)." }), _jsx("li", { children: "Higher tiers \u2013 increasing monthly surcharges added on top." }), _jsx("li", { children: "This worksheet estimates your placement using your current-year MAGI and 2025 IRMAA thresholds." })] }), _jsx("p", { className: "mt-2 text-[11px] text-gray-500", children: "Exact IRMAA amounts are set by the Social Security Administration and may change over time. Appeals and special cases are not modeled here." })] }), _jsx("p", { className: "text-[11px] text-gray-400 mt-4", children: "This simulation approximates IRMAA tiers and surcharges for educational use only and may not reflect SSA-specific calculations or appeals criteria. Not Medicare or tax advice." })] }))] }));
}
