name: CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      # Only install if package.json exists
      - name: Install deps (if present)
        run: |
          if [ -f package.json ]; then
            npm install
          else
            echo "No package.json; skipping install"
          fi
      - run: npm run lint --if-present
      - run: npm run typecheck --if-present
      - run: npm run test --if-present
      - run: npm run build --if-present
